frontend:
  targetNamespace: www-smotra-net
  image:
    repository: ghcr.io/smotra-monitoring/frontend
    pullPolicy: IfNotPresent
    tag: "v0.1.1"
  httpRoute:
    hostnames:
    - www.smotra.net

api:
  targetNamespace: api-smotra-net
  images:
    api:
      repository: ghcr.io/smotra-monitoring/api-server
      pullPolicy: IfNotPresent
      tag: "v0.4.0"
    db_migrations:
      repository: ghcr.io/smotra-monitoring/db
      pullPolicy: IfNotPresent
      tag: "v0.0.1"
    db:
      repository: timescale/timescaledb
      pullPolicy: IfNotPresent
      tag: "latest-pg16"

  httpRoute:
    hostnames:
    - api.smotra.net
  db:
    host: db-0.db
    port: 5432
    username: postgres
    password: "this_is_a_placeholder,_the_actual_password_is_stored_in_a_Kubernetes_secret"
    database: postgres
    sslmode: disable
  persistence:
      fake: value
  #   existingClaim: "postgres-data-pvc"

openapi:
  targetNamespace: openapi-smotra-net
  image:
    repository: ghcr.io/smotra-monitoring/openapi
    pullPolicy: IfNotPresent
    tag: "v0.1.0"
  httpRoute:
    hostnames:
    - openapi.smotra.net
