apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "test.labels-db" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "test.selectorLabels-db" . | nindent 4 }}
  ports:
    - port: 5432
      name: postgres
      targetPort: postgres