apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "test.labels-api" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "test.selectorLabels-api" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.targetPort }}