apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.fullname" . }}-db
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "test.labels-db" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  clusterIP: None
  selector:
    {{- include "test.selectorLabels-db" . | nindent 4 }}
  ports:
    - port: 5432
      name: postgres
      targetPort: postgres