apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "test.labels-db" . | nindent 4 }}
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      {{- include "test.selectorLabels-db" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test.selectorLabels-db" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "timescale/timescaledb:latest-pg16"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.db.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.db.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: database-password
          resources:
            limits:
              cpu: "1"
              memory: "8Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      {{- if .Values.persistence.existingClaim }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
  {{- if not .Values.persistence.existingClaim }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: 
          - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "10Gi" }}
  {{- end }}
