{{- $secretName := "db-password" -}}
{{- $existingSecret := lookup "v1" "Secret" .Values.targetNamespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ if and $existingSecret $existingSecret.data }}{{ index $existingSecret.data "database-password" }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
